name: snews
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter_bloc: ^8.1.2
  json_annotation: ^4.8.1
  http: ^0.13.6
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
